[ui.anchors]
bottom = true
left = true
right = false
top = false 

[ui.window.box]
width = 653
height = 640



[ui.window.box.scroll.list]
max_height = 550
min_height = 550
max_width = 610
min_width = 610
width = 610
height = 550

[ui.window.box.scroll.list.item.icon]
pixel_size = "42"

